ToDo/ToDo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ToDoapp.urls'))
]


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ToDo/ToDoapp/urls.py
from django . urls import path
from .import views
app_name='ToDoapp'
urlpatterns=[
path('listview/',views.TaskListview.as_view(),name='listview'),
path('detailview/<int:pk>/',views.TaskDetailview.as_view(),name='detailview'),
path('updateview/<int:pk>/',views.TaskUpdateview.as_view(),name='updateview'),
path('deleteview/<int:pk>/',views.TaskDeleteview.as_view(),name='deleteview'),
path('',views.addtask,name='addtask'),
path('delete/<int:id>/',views.delete,name='delete'),
path('update/<int:id>/',views.update,name='update'),
]

ToDo/ToDoapp/models.py
from django.db import models

# Create your models here.
class ToDotb(models.Model):
    task=models.CharField(max_length=30)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.task

ToDo/ToDoapp/forms.py
from django import forms
from .models import ToDotb

class ToDoForm(forms.ModelForm):
    class Meta:
        model=ToDotb
        fields=['task','priority','date']

ToDo/ToDoapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy

from .models import ToDotb
from .forms import ToDoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

def addtask(request):
    task=ToDotb.objects.all()
    if request.method == 'POST':
        task=request.POST.get('task')
        priority=request.POST.get('priority')
        date=request.POST.get('date')
        tasks=ToDotb(task=task,priority=priority,date=date)
        tasks.save()
        return redirect('/')
    return render(request,'Home.html',{'tasks':task})

def delete(request,id):
    task=ToDotb.objects.get(id=id)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task=ToDotb.objects.get(id=id)
    form=ToDoForm(request.POST or None,instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'tasks':task})

class TaskListview(ListView):
    model=ToDotb
    template_name = 'Home.html'
    context_object_name = 'tasks'

class TaskDetailview(DetailView):
    model=ToDotb
    template_name ='details.html'
    context_object_name = 'task'

class TaskUpdateview(UpdateView):
    model=ToDotb
    template_name ='edit.html'
    context_object_name = 'task'
    fields=('task','priority','date')
    def get_success_url(self):
        return reverse_lazy('ToDoapp:detailview',kwargs={'pk':self.object.id})

class TaskDeleteview(DeleteView):
    model=ToDotb
    template_name ='delete.html'
    success_url = reverse_lazy('ToDoapp:listview')

ToDo/templates/Home.html
{% extends 'base.html' %}
{% block content %}
<div class="contaier-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="banner">
    <div class="banner-text">
      <h1>ToDo</h1>
    </div>
    </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
<form method="post" class="p-3 shadow">
  {% csrf_token %}
  <div class="form-group">
  <input type="text" class="form-control" name="task" placeholder="Enter your task"><br>
</div>
<div class="form-group">
  <input type="text" class="form-control" name="priority" placeholder="Enter task priority"><br>
</div>
<div class="form-group">
  <input type="date" class="form-control" name="date" placeholder="Enter your date"><br>
</div>
  <input type="submit" class="btn btn-success">
</form>
</div>
<div class="col-md-6">
  <h4>Task to be Completed</h4>
  {% for i in tasks %}
<div class="shadow card">
  <div class="card-body">
  <h5 class="card-title">{{i.task}}</h5>
  <p><b>{{i.priority}}</b></p>
  <p><b>{{i.date}}</b></p>
  <a class="btn btn-danger" href="{% url 'ToDoapp:deleteview' i.id %}">Done</a>
  <a class="btn btn-success" href="{% url 'ToDoapp:updateview' i.id %}">Update</a>
</div>
</div>
  <br>
  {% endfor %}
</div>
</div>
</div>
  {% endblock %}

ToDo/templates/Hometest.html
{% extends 'base.html' %}
{% block content %}
<form method="post" >
  {% csrf_token %}
  <input type="text" name="task" placeholder="Enter your task"><br>
  <input type="text" name="priority" placeholder="Enter task priority"><br>
  <input type="submit" class="btn btn-success">
</form>
<h4>Task to be Completed</h4>
  {% for i in tasks %}
{{i.task}}</h5>
  <p><b>{{i.priority}}</b></p>
  <a class="btn btn-danger" href="delete/{{i.id}}">Done</a>
  <br>
  {% endfor %}
  {% endblock %}

ToDo/templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base_page</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

ToDo/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Are you sure this task is done?</p>
  <button class="btn btn-danger" type="submit">Confirm</button>
</form>
{% endblock %}

ToDo/templates/details.html
{% extends 'base.html' %}
{% block content %}
<div class="shadow card">
  <div class="card-body">
  <h5 class="card-title">{{task.task}}</h5>
  <p><b>{{task.priority}}</b></p>
  <p><b>{{task.date}}</b></p>
  <a class="btn btn-danger" href="{% url 'ToDoapp:deleteview' task.id %}">Done</a>
  <a class="btn btn-success" href="{% url 'ToDoapp:updateview' task.id %}">Update</a>
</div>
</div>
{% endblock %}

ToDo/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
        Task Update
        </div>
    <div class="card-body">
   <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
 <button type="submit">Update</button>
</form>
 </div>
 </div>
</div>
{% endblock %}

ToDo/templates/update.html
{% extends 'base.html' %}
{% block content %}
   <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
 <button type="submit">Update</button>
</form>
{% endblock %}